# Shaft Design [MEMS1029 HW1-3]
author: Ziang Cao
ID: ZIC25

## Problem Statement

In this exercise, I walked through the conponent selecting, demension designing, assemblying, and drawing creating. What's more, I used this time to become familiar of onShape -- the recomended online CAD tools.  

What's more, as the description of this assignment said:  
> "You may find an easier time locating commercially-available components if you scale back to a smaller size and loads than the text typically uses." 

* I simplified this by requiring the smallest diameter on whole shaft body should be larger than 20mm. And then, I put more efforts on the compoment selection and geometry designing, including the key slot.

> The wedsite for downloading the components' Free CAD: https://b2b.partcommunity.com/3d-cad-models/sso?cwid=5594  
> 
> All of my commerical components are downloaded from here.
  
* To better simulate the real-world shaft, I combined both of the modeul gear and sprocket. For instance, gears will recieve the power from another/external power source, while the power will be transmit onto a belt by sprockets for robots motion.

> The difference was clearly being stated on (by the following link): In general, a gear is a toothed wheel designed to mesh with other gears and transmit movement to them, which in turn can cause movement elsewhere. A sprocket, conversely, is a toothed wheel designed to engage and directly move a flexible indented or perforated item, like a chain or belt.
> 
>  refer to: https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjioaK2itL1AhV9kmoFHV8xBY8QFnoECBEQAw&url=https%3A%2F%2Fwww.infobloom.com%2Fwhat-is-the-difference-between-a-sprocket-and-a-gear.htm&usg=AOvVaw25Xay5WHKXrOqzwEnDe7cD

* What's more, I found the module gear do not have the key slot for locating. Hence, I use collar+key for the sprocket feasten, and only collar for the gear. I do not know wether it is allowable. But as there are so many commercial gears without key-design, it must have its reason.

* In terms of the shaft body length, I mainly follow my intuition. My rule is adding at least 30 mm to each section and round them to the upper nearest tens' multiple.

## Here is my Output in 3D view
